name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test, Report
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: |
        dotnet restore src/HouseofCat.Utilities/HouseofCat.Utilities.csproj
        dotnet restore src/HouseofCat.Hashing/HouseofCat.Hashing.csproj
        dotnet restore src/HouseofCat.Encryption/HouseofCat.Encryption.csproj
        dotnet restore src/HouseofCat.Compression/HouseofCat.Compression.csproj
        dotnet restore src/HouseofCat.Serialization/HouseofCat.Serialization.csproj
        dotnet restore src/HouseofCat.Dataflows/HouseofCat.Dataflows.csproj
        dotnet restore src/HouseofCat.RabbitMQ/HouseofCat.RabbitMQ.csproj
        dotnet restore src/HouseofCat.Data/HouseofCat.Data.csproj
        dotnet restore src/Tests/UnitTests/UnitTests.csproj

    - name: Build
      run: dotnet build src/Tests/UnitTests/UnitTests.csproj --configuration Release --no-restore

    - name: Test
      run: >-
        dotnet test src/Tests/UnitTests/UnitTests.csproj --configuration Release --no-build --verbosity normal
        -p:CollectCoverage=true
        -p:CoverletOutput=../../../coverage.cobertura.xml
        -p:CoverletOutputFormat=cobertura

    - name: Upload Coverage Report
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: 'coverage.cobertura.xml'
